# Generated by Django 5.2.13 on 2026-04-12 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cow',
            name='unique_cow_tag_per_user',
        ),
        migrations.AlterUniqueTogether(
            name='cow',
            unique_together={('user', 'tag_number')},
        ),
    ]
